### ISSUE TITLE
installing tdm option 2 did not work 

### ISSUE THREAD

**Issue by riker65** [jziolkowski/tdm#103]
Hi 
tried installing as written in option 2

pip install tdmgr

but launching is not working

`python3 tdmgr.py
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
`

python 3.8.2

**Comment by jziolkowski** [comment]
This error is not related to TDM directly, but to some apparently missing libraries required by QT5. And as such, it's outside of the scope of this project support. Sorry.

**Comment by ychasse01** [comment]
[Might want to check out this post! ](https://github.com/therecipe/qt/issues/775#issuecomment-456899597)

*** Shoutout to therecipe | for the post below ***
Could not load the Qt platform plugin "xcb" in "" even though it was found.

_This can happen if you use the docker images for example, because they don't have all the X11 stuff installed that is needed to get the "xcb" plugin working._

But you should be able to get it working with some other plugin, with something like
QT_QPA_PLATFORM=minimal
or
QT_QPA_PLATFORM=offscreen

also if you use qtminimal first, then you can save yourself some time
qtminimal && QT_QPA_PLATFORM=minimal

**Comment by Jason2866** [comment]
Closing since it is answered

**Comment by jziolkowski** [comment]
https://github.com/tasmota/tasmotizer/issues/71 please have a look and let me know

**Comment by Jason2866** [comment]
Any news? Tried?

**Comment by Jason2866** [comment]
Closing since there is no feedback
