### ISSUE TITLE
TDM-003 # Crashes if the hash character is used in an Autodiscovery string

### ISSUE THREAD

**Issue by whittedb** [jziolkowski/tdm#161]
On Windows 10 using tdmgr_0.2.11.exe, the application crashes during Autodiscovery if the hash character (#) is used in any of the patterns.

**Comment by barbudor** [comment]
At 1st look it doesn't really make sense to have # in topic patterns.
Patterns should match all of your Tasmota's full topics. If you have different ones, you need to enter all of them.

If you want to elaborate on your use case, enable debug in TDM.cfg, delete TDM.log and provide the log file after the crash.
```
[General]
loglevel=DEBUG
```

**Comment by whittedb** [comment]
You are correct in it doesn't make much sense.  But for a new user and not realizing that TDM automatically subscribed to the common patterns, I added all my custom topics with a hash and set the app to auto  connect at startup.  At that point, I was never able to remove the erroneous topics and gave up using TDM for 2 years until recently when I tried again and was persistent enough to read through the closed issues and discovered I could disable the auto-connect via the text config file.

Fixing this problem is just a question of whether you want to cater to power users only, or if you want to have less informed users be able to make mistakes and continue to use the app.

**Comment by jziolkowski** [comment]
But it already says in the very dialog that it subscribes to default topics. 

Also it's all in the project wiki. Debug options, the location of config file, etc. 

https://github.com/jziolkowski/tdm/wiki/Autodiscovery for example.

Nothing to do with power users, just users not reading what it says on the screen/docs.

**Comment by whittedb** [comment]
Agreed.  People in a hurry sometimes fail to read, or don't comprehend completely.  Filtering out the bad characters might be beneficial.

**Comment by jziolkowski** [comment]
I've tried recreating this, and indeed `#` in the discovery pattern is a culprit, but not in a way that I expected :)

The thing is that once you save `#` in the settings file, everything coming after that becomes a comment. When you close TDM after this addition, the config file becomes garbled, and since patterns are at the end of the file, they now receive a metric ton of gibberish, which is then in turn passed to functions that try and parse that into useful topics, which leads to a nice crash. Unfortunately it's a crash outside of the usual try..except catcher, because it's a crash in QT libs, to which I have no fix now.

Either way, I'm improving validation for patterns and will post PR later.
