### ISSUE TITLE
%hostname% as topic not working

### ISSUE THREAD

**Issue by jeroenst** [jziolkowski/tdm#238]
In my tasmota configuration I use %hostname% as topic. TDM tries to access 0002/%HOSTNAME%/cmnd/status 0 instead.

How can I solve this while still using the %hostname% variable in my topic?

**Comment by barbudor** [comment]
You can't
There is no %hostname% variable that can be used to define %topic%
You must set them independently to the same value

**Comment by jeroenst** [comment]
%hostname% in topic works prefectly, only not with tdm.

**Comment by jziolkowski** [comment]
this is because Tasmota knows its hostname when operating. TDM doesn't know the hostname until it receives this information from the device, after establishing its proper topic/fulltopic. It's a race condtion.

The issue will be gone when I implement native autodiscovery, but I don't have time again.

**Comment by jziolkowski** [comment]
Closing as it's Tasmota's feature, not a bug
