### ISSUE TITLE
Column size can't be changed

### ISSUE THREAD

**Issue by GuybrushX** [jziolkowski/tdm#64]
In the Devices list (I think it should be Device list without the plural "s" but not sure) the column size can't be changed. Size should be adjustable.

**Comment by jziolkowski** [comment]
This is not a code issue. Such feature requests should be directed to Discord channel.

Also, I've been considering this, but as I'm reworking the whole list display, this feature will be done later (if ever, because don't see a reason enough to add quite a lot of code for a feature that provides very little advantage)
