### ISSUE TITLE
Configuration ist not saved in ~/.tdm

### ISSUE THREAD

**Issue by eku** [jziolkowski/tdm#74]
I'm using TDM under Linux and expect that it stores its configutation under ```~/.tdm```. Instead it uses ```~/TDM``` which is annoying, because it messes up the home directory. Please follow the UNIX/Linux guides for placing configuration files. TIA.

**Comment by jziolkowski** [comment]
Yeah, you are correct. I should change that in next release.

**Comment by eku** [comment]
@jziolkowski Please also implement a migration of existing configuration under ~/TDM to ~/.tdm, so that existing settings are taken over. The easiest way is probably to rename the directory, if it exists.

**Comment by eku** [comment]
#83 does not fix the issue for me. Still writes to ~/TDM/. Using tdm 0.2.8.

**Comment by eku** [comment]
I wanted to ask politely what is stopping you from solving this issue?

**Comment by jziolkowski** [comment]
I politely respond that it's a complete lack of spare time :)

**Comment by jziolkowski** [comment]
Since you asked politely :)

Please check the current develop version. I've changed the settings location. The app (for now) will use .ini files, but stored in OS-dependent user settings directory, as outlined at https://doc.qt.io/qt-5/qsettings.html#fallback-mechanism

On linux, this means it will be ~/.config/tdm

not planning on adding a migration, since it's either very simple manual file operation, or very simple input of few details in TDM.

**Comment by jziolkowski** [comment]
@eku ^^

**Comment by jziolkowski** [comment]
Closing with no feedback
