### ISSUE TITLE
Crash when sorting by uptime

### ISSUE THREAD

**Issue by swampdogmash** [jziolkowski/tdm#96]
Hi, only recenty found TDM and impressed so far with the effort taken to produce something to consolidate all the devices :)

I've noticed that when I click the column title to sort by "uptime" (certainly in the main initial window and in the other tabs where it appears also) the app just closes after a few seconds.

I'm running the 0.2.6 release on windows 10 64bit - version 2004.

**Comment by swampdogmash** [comment]
Just done some more testing with this and it appears that now i have upgraded all my tasmota instances bar 1 to 8.3.1 the sort now works.  There were several instances of version 6.5 and 5.x in the list previously and I could not sort at all. Could this be related to the format of time data received from the older versions? Is there a statement somewhere about the oldset supported version of teasmota in TDM?

**Comment by meingraham** [comment]
https://github.com/jziolkowski/tdm#minimum-fully-supported-tasmota-firmware-version-66017

**Comment by swampdogmash** [comment]
Not sure an incorrect version should cause the app to crash though... "supported" is one thing - "broken by" shouldn't be a thing surely :P

**Comment by meingraham** [comment]
The issue is that the structure of many status messages changes from version to version and accounting for all of the permutations of older versions would entail a great deal of effort based on the pace of Tasmota development. 6.6.0.17 was only nine months ago... but Tasmota years are larger than dog years :wink: Because this is a free tool created on @jziolkowski personal time, there's just so much he can do... and TDM has done a great deal indeed! But, this being an opensource project, fixes and enhancements from the community are always welcome through pull requests.

In the interim, having the requirements documented in the product description is as good as it's going to get unfortunately.
